spring:
  application:
    name: configServer

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sarkarsnejuti/SpringBoot_Microservice_Project.git"
          default-label: master
          search-paths:
            - configServer/src/main/resources/config
          timeout: 90
          clone-on-start: true
          force-pull: true

server:
  port: 8080